### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'rotation')

### ISSUE THREAD

**Issue by Samonnite** [materialsproject/mp-react-components#635]
https://materialsproject.github.io/mp-react-components/?path=/story/crystal-toolkit-crystaltoolkitscene--basic
![image](https://user-images.githubusercontent.com/24725952/172522867-4651c3d5-2319-4c36-96aa-9a7d62148578.png)

```
TypeError: Cannot read properties of undefined (reading 'rotation')
    at new InsetHelper (https://materialsproject.github.io/mp-react-components/main.0a4797d2.iframe.bundle.js:1:142840)
    at new Scene (https://materialsproject.github.io/mp-react-components/main.0a4797d2.iframe.bundle.js:1:160581)
    at https://materialsproject.github.io/mp-react-components/main.0a4797d2.iframe.bundle.js:1:196368
    at commitHookEffectListMount (https://materialsproject.github.io/mp-react-components/942.9c0eb5a4.iframe.bundle.js:2:4841045)
    at commitPassiveHookEffects (https://materialsproject.github.io/mp-react-components/942.9c0eb5a4.iframe.bundle.js:2:4842147)
    at HTMLUnknownElement.callCallback (https://materialsproject.github.io/mp-react-components/942.9c0eb5a4.iframe.bundle.js:2:4496053)
    at Object.invokeGuardedCallbackImpl (https://materialsproject.github.io/mp-react-components/942.9c0eb5a4.iframe.bundle.js:2:4496571)
    at invokeGuardedCallback (https://materialsproject.github.io/mp-react-components/942.9c0eb5a4.iframe.bundle.js:2:4497775)
    at flushPassiveEffectsImpl (https://materialsproject.github.io/mp-react-components/942.9c0eb5a4.iframe.bundle.js:2:4893102)
    at unstable_runWithPriority (https://materialsproject.github.io/mp-react-components/942.9c0eb5a4.iframe.bundle.js:2:5912597)
```

**Comment by JoshDLane** [comment]
any progress on this? is it just an issue in storybook?

**Comment by Aaronphy** [comment]
> any progress on this? is it just an issue in storybook?

Hi, Do you know how to parse the CIF  to the Scene JSON?
